baseurl = "http://fpsiholog.org"
languageCode = "ru"
defaultcontentlanguage = "ru"
title = "Дом проектов Нелли Лисицы"
# Enable comments by entering your Disqus shortname
disqusShortname = "sunnybunnyf"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-93042591-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[taxonomies]
tag = "tags"
category = "categories"


[permalinks]
    post = "/:section/:year/:month/:day/:slug"
    podcast = "/:section/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Нелли Лисица"
    bio = "Хороший человек - Психолог"
    location = "Earth"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    logo = "css/images/logo.png"
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
# [[params.menu]]
#     before = true
#     label  = "Главная"
#     link   = "/"

[[params.menu]]
    before = true
    label  = "Подкаст \"Психология в разрезе\""
    link   = "categories/психология-в-разрезе/"


[[params.menu]]
    before = true
    label  = "Фотографии"
    link   = "gallery/"

[[params.menu]]
    before = false
    label  = "Все разделы"
    link   = "categories/"

[[params.menu]]
    before = false
    label  = "О сайте"
    link   = "about/"


# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://vk.com/sunnybunnyf"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = ""
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    vk              = "SunnyBunnyF"
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "SunnyBunnyF"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "SunnyBunnyF"

# Enable and disable widgets for the right sidebar
[params.widgets]
    links = true
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
